// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsaogiyetehavzutiscc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYW9naXlldGVoYXZ6dXRpc2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Njk1NTEsImV4cCI6MjA2NTM0NTU1MX0._i9McAaPGNftv6sFW1x7u2ys7r5wgQVAfRNFfbPje0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);